// ============================================================================
// tuidaw - Native Audio Engine (miniaudio-based)
// ============================================================================
// Cross-platform audio I/O via miniaudio. Compiled as a shared library,
// called from TypeScript via Bun FFI.
//
// Architecture:
//   - Single playback device with a mixing callback
//   - Per-track sample buffers with volume/pan (atomic parameter changes)
//   - Per-track capture devices for recording
//   - Click generator inline in the playback callback
//   - Sample-accurate playhead tracking
//   - Loop region handled in the callback
// ============================================================================

#define MINIAUDIO_IMPLEMENTATION
#include "miniaudio.h"

#include <string.h>
#include <stdlib.h>
#include <math.h>
#include <stdatomic.h>

// ── Constants ───────────────────────────────────────────────────────────────

#define SAMPLE_RATE       48000
#define MAX_TRACKS        64
#define MAX_DEVICE_NAME   256
#define RECORDING_BUF_SEC 600   // 10 minutes max recording per track
#define RECORDING_BUF_LEN (SAMPLE_RATE * RECORDING_BUF_SEC)

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

// ── WSOLA Constants ─────────────────────────────────────────────────────────
// WSOLA (Waveform Similarity Overlap-Add) for pitch-preserving time stretch.
// Window ~23ms at 48kHz, 50% overlap, ±search range for best alignment.

#define WSOLA_WINDOW     1024       // analysis window size (samples)
#define WSOLA_HOP        512        // output hop size (WSOLA_WINDOW / 2)
#define WSOLA_SEARCH     256        // ±search range for similarity matching
#define WSOLA_OUTBUF_LEN 2048       // circular output buffer per track

// ── Track State ─────────────────────────────────────────────────────────────

// Per-track WSOLA time-stretch state
typedef struct {
    double  input_pos;               // fractional input read position (in source samples)
    float   window_buf[WSOLA_WINDOW]; // Hann-windowed overlap buffer
    float   out_buf[WSOLA_OUTBUF_LEN]; // circular output buffer
    int     out_write;               // write position in out_buf
    int     out_read;                // read position in out_buf
    int     out_avail;               // samples available in out_buf
    int     initialized;             // has been reset for current transport
} WsolaState;

typedef struct {
    int           active;            // slot in use
    int           id;                // track ID (from JS)
    float*        samples;           // playback sample buffer (mono, owned by JS — NOT freed here)
    int           samples_len;       // length of samples buffer
    _Atomic float volume;            // 0.0 - 1.0
    _Atomic float pan;               // -1.0 (L) to 1.0 (R)
    _Atomic int   muted;             // boolean
    _Atomic int   solo;              // boolean

    // Recording state
    _Atomic int   recording;         // currently recording
    float*        rec_buffer;        // ring buffer for captured audio (owned by us)
    _Atomic int   rec_write_pos;     // write position in rec_buffer
    int           rec_device_index;  // miniaudio capture device index (-1 = default)
    ma_device     rec_device;        // capture device (active only while recording)
    int           rec_device_active; // is rec_device initialized and started

    // WSOLA time-stretch state
    WsolaState    wsola;
} TrackState;

// ── Engine State ────────────────────────────────────────────────────────────

typedef struct {
    ma_context    context;
    ma_device     playback_device;
    int           playback_active;

    TrackState    tracks[MAX_TRACKS];

    _Atomic int   playing;               // transport running
    _Atomic long  playhead_samples;      // current playhead position (in samples)
    long          transport_start_pos;   // playhead position when transport started

    // Click state
    _Atomic int   click_enabled;
    _Atomic float click_volume;           // 0.0 - 2.0+ (allows above 100%)
    _Atomic float click_pan;              // -1.0 (L) to 1.0 (R), 0.0 = center

    // Click sample buffer (owned by native engine — allocated via malloc/realloc).
    // Contains a long pre-rendered click track: click tones (960 samples of
    // 1kHz sine + 20ms decay) placed at correct beat positions, with silence
    // between them. The buffer is generated by tuidaw_generate_click(bpm,
    // duration_frames) and is long enough for the full project duration or
    // 10 minutes (whichever is requested). The native callback reads
    // click_samples[counter] with a bounds check — no modulo, no floating-point
    // BPM math. Beat positions use GCD-exact integer arithmetic for zero drift.
    float*        click_samples;          // owned by C (malloc'd), freed on regenerate/deinit
    _Atomic int   click_samples_len;      // total number of samples in buffer
    int           click_samples_capacity; // allocated capacity (for realloc efficiency)
    _Atomic long  click_frame_counter;    // output frame counter for click timing (reset on play/seek)

    // Loop state
    _Atomic long  loop_start;            // -1 = no loop
    _Atomic long  loop_end;              // -1 = no loop

    // Playback speed (1.0 = normal, 0.5 = half speed, 2.0 = double)
    _Atomic float playback_speed;

    // Output device
    int           output_device_index;   // -1 = default (requested)
    int           active_device_index;   // -1 = default (currently active on playback_device)
    int           use_null_backend;      // force null (silent) backend for tests

    // Device info cache
    ma_device_info* playback_infos;
    ma_uint32       playback_count;
    ma_device_info* capture_infos;
    ma_uint32       capture_count;
} EngineState;

static EngineState g_engine;

// ── Helpers ─────────────────────────────────────────────────────────────────

static TrackState* find_track(int id) {
    for (int i = 0; i < MAX_TRACKS; i++) {
        if (g_engine.tracks[i].active && g_engine.tracks[i].id == id) {
            return &g_engine.tracks[i];
        }
    }
    return NULL;
}

static TrackState* find_free_slot(void) {
    for (int i = 0; i < MAX_TRACKS; i++) {
        if (!g_engine.tracks[i].active) {
            return &g_engine.tracks[i];
        }
    }
    return NULL;
}

static int has_any_solo(void) {
    for (int i = 0; i < MAX_TRACKS; i++) {
        if (g_engine.tracks[i].active && atomic_load(&g_engine.tracks[i].solo)) {
            return 1;
        }
    }
    return 0;
}

// ── WSOLA Helpers ───────────────────────────────────────────────────────────
// Pitch-preserving time stretch using Waveform Similarity Overlap-Add.
// Each track has its own WSOLA state so tracks can be independently stretched.

// Reset WSOLA state for a track (called on transport start or speed change)
static void wsola_reset(WsolaState* ws, double start_pos) {
    ws->input_pos = start_pos;
    ws->out_write = 0;
    ws->out_read = 0;
    ws->out_avail = 0;
    ws->initialized = 1;
    memset(ws->window_buf, 0, sizeof(ws->window_buf));
    memset(ws->out_buf, 0, sizeof(ws->out_buf));
}

// Hann window coefficient for position i in window of size n
static inline float hann(int i, int n) {
    return 0.5f * (1.0f - cosf(2.0f * (float)M_PI * (float)i / (float)(n - 1)));
}

// Read a sample from the track with bounds checking (returns 0 outside range)
static inline float safe_read(const float* samples, int len, long pos) {
    if (pos < 0 || pos >= len) return 0.0f;
    return samples[pos];
}

// Find the best alignment offset within ±WSOLA_SEARCH of the target position
// by maximizing cross-correlation with the previous window tail.
// Returns the offset that gives the best overlap match.
static int wsola_find_best_offset(const float* samples, int len,
                                   long target_pos, const float* prev_tail, int tail_len) {
    int best_offset = 0;
    float best_corr = -1e30f;

    // If no previous tail data, just use target position directly
    if (tail_len <= 0) return 0;

    for (int offset = -WSOLA_SEARCH; offset <= WSOLA_SEARCH; offset++) {
        long pos = target_pos + offset;
        float corr = 0.0f;
        float norm1 = 0.0f;
        float norm2 = 0.0f;

        // Compare tail of previous window with beginning of candidate window
        // Use a subset for speed (every 4th sample)
        for (int i = 0; i < tail_len; i += 4) {
            float s1 = prev_tail[i];
            float s2 = safe_read(samples, len, pos + i);
            corr += s1 * s2;
            norm1 += s1 * s1;
            norm2 += s2 * s2;
        }

        float denom = sqrtf(norm1 * norm2 + 1e-20f);
        float normalized = corr / denom;

        if (normalized > best_corr) {
            best_corr = normalized;
            best_offset = offset;
        }
    }

    return best_offset;
}

// Generate WSOLA output samples for a track. Fills the circular output buffer.
// speed: playback speed (1.0 = normal, <1 = slower, >1 = faster)
// The input position advances by speed * WSOLA_HOP per output hop.
// When loop boundaries are provided (loop_start >= 0), input_pos wraps at
// loop_end back to loop_start so the WSOLA reader stays within the loop region.
static void wsola_generate(WsolaState* ws, const float* samples, int len,
                           float speed, long loop_start, long loop_end) {
    int has_loop = (loop_start >= 0 && loop_end > loop_start);

    // Generate enough output to fill a reasonable amount (at least WSOLA_HOP samples)
    while (ws->out_avail < WSOLA_OUTBUF_LEN - WSOLA_WINDOW) {
        long target_input = (long)ws->input_pos;

        // Wrap input_pos at loop boundary (content-space)
        if (has_loop && target_input >= loop_end) {
            long loop_len = loop_end - loop_start;
            long overshoot = target_input - loop_end;
            ws->input_pos = (double)(loop_start + (overshoot % loop_len));
            target_input = (long)ws->input_pos;
            // Clear overlap buffer on loop wrap to avoid cross-correlation
            // artifacts between end and start of loop
            memset(ws->window_buf, 0, sizeof(ws->window_buf));
        }

        // If we're past the end of the audio (no loop), output silence
        if (target_input >= len) {
            // Write silence to fill buffer
            for (int i = 0; i < WSOLA_HOP; i++) {
                ws->out_buf[ws->out_write] = 0.0f;
                ws->out_write = (ws->out_write + 1) % WSOLA_OUTBUF_LEN;
                ws->out_avail++;
            }
            ws->input_pos += (double)WSOLA_HOP * speed;
            return;
        }

        // Find best alignment by cross-correlating with previous window tail
        // The previous window tail is the second half of window_buf
        int best_offset = wsola_find_best_offset(
            samples, len, target_input,
            ws->window_buf + WSOLA_HOP,  // tail = second half of previous window
            WSOLA_HOP
        );

        long aligned_pos = target_input + best_offset;

        // Extract and window the new segment
        float new_window[WSOLA_WINDOW];
        for (int i = 0; i < WSOLA_WINDOW; i++) {
            new_window[i] = safe_read(samples, len, aligned_pos + i) * hann(i, WSOLA_WINDOW);
        }

        // Overlap-add: first half overlaps with tail of previous window,
        // second half is the new tail for next iteration
        for (int i = 0; i < WSOLA_HOP; i++) {
            // Overlap region: blend previous tail with start of new window
            float blended = ws->window_buf[WSOLA_HOP + i] + new_window[i];
            ws->out_buf[ws->out_write] = blended;
            ws->out_write = (ws->out_write + 1) % WSOLA_OUTBUF_LEN;
            ws->out_avail++;
        }

        // Store new window for next iteration's overlap
        memcpy(ws->window_buf, new_window, sizeof(float) * WSOLA_WINDOW);

        // Advance input position by hop * speed
        // speed < 1: input advances slower → audio stretches (slower playback)
        // speed > 1: input advances faster → audio compresses (faster playback)
        ws->input_pos += (double)WSOLA_HOP * speed;
    }
}

// Read one sample from the WSOLA output buffer
static float wsola_read_sample(WsolaState* ws) {
    if (ws->out_avail <= 0) return 0.0f;
    float s = ws->out_buf[ws->out_read];
    ws->out_read = (ws->out_read + 1) % WSOLA_OUTBUF_LEN;
    ws->out_avail--;
    return s;
}

// ── Playback Callback ───────────────────────────────────────────────────────
// Called on the audio thread. Mixes all tracks + click into the output buffer.
// When playback_speed != 1.0, uses WSOLA for pitch-preserving time stretch.
//
// Click is now a pre-baked buffer (one full beat: tone + silence) owned
// by JS. The native engine reads it with simple integer modulo
// (counter % buffer_length) — no BPM math in the callback, no fmod,
// no floating-point precision issues. When BPM changes, JS regenerates
// the buffer with a new length.

static void playback_callback(ma_device* pDevice, void* pOutput, const void* pInput, ma_uint32 frameCount) {
    (void)pDevice;
    (void)pInput;

    float* out = (float*)pOutput;
    memset(out, 0, frameCount * 2 * sizeof(float));  // stereo output

    if (!atomic_load(&g_engine.playing)) return;

    long playhead = atomic_load(&g_engine.playhead_samples);
    long loop_start = atomic_load(&g_engine.loop_start);
    long loop_end = atomic_load(&g_engine.loop_end);
    float speed = atomic_load(&g_engine.playback_speed);

    // Clamp speed to sane range
    if (speed < 0.25f) speed = 0.25f;
    if (speed > 2.0f) speed = 2.0f;

    int any_solo = has_any_solo();

    // Click state
    int click_enabled = atomic_load(&g_engine.click_enabled);
    float click_vol = atomic_load(&g_engine.click_volume);
    float click_pan = atomic_load(&g_engine.click_pan);
    float* click_samples = g_engine.click_samples;
    int click_samples_len = atomic_load(&g_engine.click_samples_len);

    int use_wsola = (speed < 0.99f || speed > 1.01f);

    // If using WSOLA, ensure all active tracks have initialized state
    if (use_wsola) {
        for (int t = 0; t < MAX_TRACKS; t++) {
            TrackState* tk = &g_engine.tracks[t];
            if (!tk->active) continue;
            if (!tk->wsola.initialized) {
                wsola_reset(&tk->wsola, (double)playhead);
            }
            // Pre-generate WSOLA output for this callback
            // Loop boundaries are passed in content-space so wsola_generate
            // wraps input_pos at loop_end back to loop_start.
            if (tk->samples && tk->samples_len > 0 &&
                !atomic_load(&tk->muted) &&
                !(any_solo && !atomic_load(&tk->solo)) &&
                !atomic_load(&tk->recording)) {
                wsola_generate(&tk->wsola, tk->samples, tk->samples_len,
                               speed, loop_start, loop_end);
            }
        }

        // (Click no longer uses WSOLA — it uses an output-space frame counter
        // so the tone is never pitch-shifted regardless of playback speed.)
    }

    for (ma_uint32 frame = 0; frame < frameCount; frame++) {
        long pos = playhead + (long)frame;

        // Loop handling: wrap position (for non-WSOLA playback)
        if (loop_start >= 0 && loop_end > loop_start && pos >= loop_end) {
            long loop_len = loop_end - loop_start;
            long overshoot = pos - loop_end;
            pos = loop_start + (overshoot % loop_len);
        }

        float left = 0.0f;
        float right = 0.0f;

        // Mix tracks
        for (int t = 0; t < MAX_TRACKS; t++) {
            TrackState* tk = &g_engine.tracks[t];
            if (!tk->active) continue;
            if (atomic_load(&tk->muted)) continue;
            if (any_solo && !atomic_load(&tk->solo)) continue;
            if (atomic_load(&tk->recording)) continue;
            if (!tk->samples || tk->samples_len == 0) continue;

            float sample;
            if (use_wsola) {
                // Read from WSOLA output buffer (pitch-preserved time-stretched audio)
                sample = wsola_read_sample(&tk->wsola);
            } else {
                // Normal playback: direct sample read
                if (pos < 0 || pos >= tk->samples_len) continue;
                sample = tk->samples[pos];
            }

            float vol = atomic_load(&tk->volume);
            float pan = atomic_load(&tk->pan);

            // Equal-power panning
            float left_gain = cosf(((pan + 1.0f) / 2.0f) * (float)(M_PI / 2.0));
            float right_gain = sinf(((pan + 1.0f) / 2.0f) * (float)(M_PI / 2.0));

            left  += sample * vol * left_gain;
            right += sample * vol * right_gain;
        }

        // Click (metronome) — pre-rendered long buffer in OUTPUT-SPACE.
        // The click_samples buffer contains the full click track: click tones
        // placed at exact beat positions (at display BPM) with silence between.
        // We index by click_frame_counter (output-space time).
        // On loop wrap, the counter is reset to correspond to loop_start.
        if (click_enabled && click_samples && click_samples_len > 0) {
            long counter = atomic_load(&g_engine.click_frame_counter) + (long)frame;
            if (counter >= 0 && counter < (long)click_samples_len) {
                float click_sample = click_samples[counter] * click_vol;

                // Equal-power panning for click
                float cl_left  = cosf(((click_pan + 1.0f) / 2.0f) * (float)(M_PI / 2.0));
                float cl_right = sinf(((click_pan + 1.0f) / 2.0f) * (float)(M_PI / 2.0));
                left  += click_sample * cl_left;
                right += click_sample * cl_right;
            }
        }

        // Clamp
        if (left > 1.0f) left = 1.0f;
        if (left < -1.0f) left = -1.0f;
        if (right > 1.0f) right = 1.0f;
        if (right < -1.0f) right = -1.0f;

        out[frame * 2 + 0] = left;
        out[frame * 2 + 1] = right;
    }

    // Advance playhead.
    // All coordinates are in content-space (source sample positions).
    // When WSOLA is active, the playhead tracks wsola.input_pos which
    // advances at speed * hop per output hop — so at 0.5x speed, the
    // playhead advances half as fast through the source material.
    // When WSOLA is not active, playhead == wall-clock == content-space
    // (since speed is 1.0).
    long new_playhead;

    if (use_wsola) {
        // Derive playhead from WSOLA input_pos (content-space).
        // This ensures playhead always tracks the actual source position
        // being read, regardless of speed.
        new_playhead = playhead + (long)frameCount; // fallback
        for (int t = 0; t < MAX_TRACKS; t++) {
            TrackState* tk = &g_engine.tracks[t];
            if (!tk->active) continue;
            if (atomic_load(&tk->muted)) continue;
            if (atomic_load(&tk->recording)) continue;
            if (!tk->samples || tk->samples_len == 0) continue;
            if (tk->wsola.initialized) {
                new_playhead = (long)tk->wsola.input_pos;
                break;
            }
        }

        // Handle loop wrapping (input_pos is already wrapped by wsola_generate,
        // but clamp to be safe)
        if (loop_start >= 0 && loop_end > loop_start) {
            if (new_playhead >= loop_end) {
                long loop_len = loop_end - loop_start;
                long overshoot = new_playhead - loop_end;
                new_playhead = loop_start + (overshoot % loop_len);
            }
            if (new_playhead < loop_start) {
                new_playhead = loop_start;
            }
        }
    } else {
        // No WSOLA (speed == 1.0): playhead advances in real-time
        // which equals content-space when speed is 1.0
        new_playhead = playhead + (long)frameCount;

        if (loop_start >= 0 && loop_end > loop_start) {
            if (new_playhead >= loop_end) {
                long loop_len = loop_end - loop_start;
                long overshoot = new_playhead - loop_end;
                new_playhead = loop_start + (overshoot % loop_len);
            }
        }
    }

    // Advance click counter with loop-wrap handling.
    // The click counter is ABSOLUTE output-space (content position / speed).
    // The click buffer contains tones at GCD-exact beat positions in output-space.
    //
    // On loop: the click counter wraps when it reaches the output-space position
    // corresponding to loop_end in content-space. Since the counter is absolute:
    //   output_end = loop_end / speed
    //   output_start = loop_start / speed
    // The counter wraps from output_end back to output_start, so the click
    // re-aligns with the content beat grid on each loop iteration.
    //
    // We detect the wrap from the counter itself (not from playhead comparison),
    // because WSOLA look-ahead can cause the playhead to wrap before the output
    // actually reaches the loop boundary.
    if (click_enabled) {
        long old_counter = atomic_load(&g_engine.click_frame_counter);
        long new_counter = old_counter + (long)frameCount;

        if (loop_start >= 0 && loop_end > loop_start && speed > 0.01f) {
            double loop_output_end = (double)loop_end / (double)speed;
            double loop_output_start = (double)loop_start / (double)speed;
            double loop_output_len = loop_output_end - loop_output_start;

            if (loop_output_len > 0 && (double)new_counter >= loop_output_end) {
                // Wrap counter to loop start, preserving fractional overshoot
                double overshoot = (double)new_counter - loop_output_end;
                double wrapped = loop_output_start + fmod(overshoot, loop_output_len);
                new_counter = (long)(wrapped + 0.5);
            }
        }

        atomic_store(&g_engine.click_frame_counter, new_counter);
    }

    atomic_store(&g_engine.playhead_samples, new_playhead);
}

// ── Capture Callback (per-track recording) ──────────────────────────────────

static void capture_callback(ma_device* pDevice, void* pOutput, const void* pInput, ma_uint32 frameCount) {
    (void)pOutput;

    TrackState* tk = (TrackState*)pDevice->pUserData;
    if (!tk || !atomic_load(&tk->recording) || !tk->rec_buffer) return;

    const float* input = (const float*)pInput;
    int write_pos = atomic_load(&tk->rec_write_pos);

    for (ma_uint32 i = 0; i < frameCount; i++) {
        if (write_pos >= RECORDING_BUF_LEN) break;
        tk->rec_buffer[write_pos] = input[i];
        write_pos++;
    }

    atomic_store(&tk->rec_write_pos, write_pos);
}

// ── Exported API ────────────────────────────────────────────────────────────

#ifdef _WIN32
#define EXPORT __declspec(dllexport)
#else
#define EXPORT __attribute__((visibility("default")))
#endif

// Initialize the audio engine. Returns 0 on success, -1 on failure.
EXPORT int tuidaw_init(void) {
    memset(&g_engine, 0, sizeof(g_engine));
    atomic_store(&g_engine.loop_start, -1);
    atomic_store(&g_engine.loop_end, -1);
    atomic_store(&g_engine.click_volume, 0.5f);
    atomic_store(&g_engine.click_pan, 0.0f);
    atomic_store(&g_engine.click_samples_len, 0);
    g_engine.click_samples = NULL;
    atomic_store(&g_engine.click_frame_counter, 0L);
    atomic_store(&g_engine.playback_speed, 1.0f);
    g_engine.output_device_index = -1;
    g_engine.active_device_index = -1;

    ma_context_config ctxConfig = ma_context_config_init();
    if (ma_context_init(NULL, 0, &ctxConfig, &g_engine.context) != MA_SUCCESS) {
        return -1;
    }

    // Enumerate devices
    ma_context_get_devices(&g_engine.context,
        &g_engine.playback_infos, &g_engine.playback_count,
        &g_engine.capture_infos, &g_engine.capture_count);

    return 0;
}

// Initialize the audio engine with the null (silent) backend.
// Identical to tuidaw_init() but forces ma_backend_null so no audio is played.
// The playback callback still runs on a timer thread, so playhead/WSOLA work normally.
// Intended for automated tests.
EXPORT int tuidaw_init_null(void) {
    memset(&g_engine, 0, sizeof(g_engine));
    atomic_store(&g_engine.loop_start, -1);
    atomic_store(&g_engine.loop_end, -1);
    atomic_store(&g_engine.click_volume, 0.5f);
    atomic_store(&g_engine.click_pan, 0.0f);
    atomic_store(&g_engine.click_samples_len, 0);
    g_engine.click_samples = NULL;
    atomic_store(&g_engine.click_frame_counter, 0L);
    atomic_store(&g_engine.playback_speed, 1.0f);
    g_engine.output_device_index = -1;
    g_engine.active_device_index = -1;
    g_engine.use_null_backend = 1;

    ma_backend backends[] = { ma_backend_null };
    ma_context_config ctxConfig = ma_context_config_init();
    if (ma_context_init(backends, 1, &ctxConfig, &g_engine.context) != MA_SUCCESS) {
        return -1;
    }

    // Enumerate devices (will return null backend virtual devices)
    ma_context_get_devices(&g_engine.context,
        &g_engine.playback_infos, &g_engine.playback_count,
        &g_engine.capture_infos, &g_engine.capture_count);

    return 0;
}

// Shut down the audio engine.
EXPORT void tuidaw_deinit(void) {
    // Stop transport
    atomic_store(&g_engine.playing, 0);

    // Free click buffer (owned by native engine)
    atomic_store(&g_engine.click_samples_len, 0);
    // Free click buffer only if native-owned (capacity > 0 means we malloc'd it)
    if (g_engine.click_samples && g_engine.click_samples_capacity > 0) {
        free(g_engine.click_samples);
    }
    g_engine.click_samples = NULL;
    g_engine.click_samples_capacity = 0;

    // Stop and free all recording devices
    for (int i = 0; i < MAX_TRACKS; i++) {
        TrackState* tk = &g_engine.tracks[i];
        if (tk->rec_device_active) {
            ma_device_uninit(&tk->rec_device);
            tk->rec_device_active = 0;
        }
        if (tk->rec_buffer) {
            free(tk->rec_buffer);
            tk->rec_buffer = NULL;
        }
        tk->active = 0;
    }

    // Stop playback device
    if (g_engine.playback_active) {
        ma_device_uninit(&g_engine.playback_device);
        g_engine.playback_active = 0;
    }

    ma_context_uninit(&g_engine.context);
}

// ── Device Enumeration ──────────────────────────────────────────────────────

// Refresh device list. Returns 0 on success.
EXPORT int tuidaw_refresh_devices(void) {
    // Re-enumerate
    ma_context_get_devices(&g_engine.context,
        &g_engine.playback_infos, &g_engine.playback_count,
        &g_engine.capture_infos, &g_engine.capture_count);
    return 0;
}

// Get number of playback or capture devices.
// type: 0 = playback (output), 1 = capture (input)
EXPORT int tuidaw_get_device_count(int type) {
    if (type == 0) return (int)g_engine.playback_count;
    return (int)g_engine.capture_count;
}

// Get device name. Writes into the provided buffer.
// Returns 0 on success, -1 on failure.
EXPORT int tuidaw_get_device_name(int type, int index, char* out_name, int max_len) {
    ma_device_info* infos;
    ma_uint32 count;
    if (type == 0) {
        infos = g_engine.playback_infos;
        count = g_engine.playback_count;
    } else {
        infos = g_engine.capture_infos;
        count = g_engine.capture_count;
    }
    if (index < 0 || (ma_uint32)index >= count) return -1;
    strncpy(out_name, infos[index].name, max_len - 1);
    out_name[max_len - 1] = '\0';
    return 0;
}

// Check if a device is the system default.
// Returns 1 if default, 0 otherwise.
EXPORT int tuidaw_is_device_default(int type, int index) {
    ma_device_info* infos;
    ma_uint32 count;
    if (type == 0) {
        infos = g_engine.playback_infos;
        count = g_engine.playback_count;
    } else {
        infos = g_engine.capture_infos;
        count = g_engine.capture_count;
    }
    if (index < 0 || (ma_uint32)index >= count) return 0;
    return infos[index].isDefault ? 1 : 0;
}

// Set the output device index. -1 = default.
// Takes effect on next tuidaw_start_playback_device() call.
EXPORT void tuidaw_set_output_device(int index) {
    g_engine.output_device_index = index;
}

// Get the currently active output device index (-1 = default).
// This is the device that was used when tuidaw_start_playback_device() last succeeded.
EXPORT int tuidaw_get_active_device_index(void) {
    return g_engine.active_device_index;
}

// ── Playback Device Management ──────────────────────────────────────────────

// Start (or restart) the playback device. Must be called before playing.
// Returns 0 on success.
EXPORT int tuidaw_start_playback_device(void) {
    // If already active, stop first
    if (g_engine.playback_active) {
        ma_device_uninit(&g_engine.playback_device);
        g_engine.playback_active = 0;
        g_engine.active_device_index = -1;
    }

    ma_device_config config = ma_device_config_init(ma_device_type_playback);
    config.playback.format   = ma_format_f32;
    config.playback.channels = 2;
    config.sampleRate        = SAMPLE_RATE;
    config.dataCallback      = playback_callback;
    config.periodSizeInFrames = 256;  // ~5.3ms latency

    if (g_engine.output_device_index >= 0 &&
        (ma_uint32)g_engine.output_device_index < g_engine.playback_count) {
        config.playback.pDeviceID = &g_engine.playback_infos[g_engine.output_device_index].id;
    }

    if (ma_device_init(&g_engine.context, &config, &g_engine.playback_device) != MA_SUCCESS) {
        return -1;
    }

    if (ma_device_start(&g_engine.playback_device) != MA_SUCCESS) {
        ma_device_uninit(&g_engine.playback_device);
        return -1;
    }

    g_engine.playback_active = 1;
    g_engine.active_device_index = g_engine.output_device_index;
    return 0;
}

// Stop the playback device.
EXPORT void tuidaw_stop_playback_device(void) {
    if (g_engine.playback_active) {
        ma_device_uninit(&g_engine.playback_device);
        g_engine.playback_active = 0;
        g_engine.active_device_index = -1;
    }
}

// ── Track Management ────────────────────────────────────────────────────────

// Register a track. Returns 0 on success, -1 if no slots available.
EXPORT int tuidaw_add_track(int id) {
    if (find_track(id)) return 0;  // already exists
    TrackState* tk = find_free_slot();
    if (!tk) return -1;

    memset(tk, 0, sizeof(TrackState));
    tk->active = 1;
    tk->id = id;
    atomic_store(&tk->volume, 0.8f);
    atomic_store(&tk->pan, 0.0f);
    atomic_store(&tk->muted, 0);
    atomic_store(&tk->solo, 0);
    atomic_store(&tk->recording, 0);
    tk->rec_device_index = -1;
    tk->rec_device_active = 0;
    tk->rec_buffer = NULL;
    tk->samples = NULL;
    tk->samples_len = 0;
    return 0;
}

// Remove a track.
EXPORT void tuidaw_remove_track(int id) {
    TrackState* tk = find_track(id);
    if (!tk) return;

    // Stop recording if active
    if (tk->rec_device_active) {
        ma_device_uninit(&tk->rec_device);
        tk->rec_device_active = 0;
    }
    if (tk->rec_buffer) {
        free(tk->rec_buffer);
        tk->rec_buffer = NULL;
    }

    tk->active = 0;
    tk->samples = NULL;
    tk->samples_len = 0;
}

// Set a track's sample buffer. The pointer must remain valid until
// tuidaw_set_track_samples is called again or the track is removed.
// The memory is owned by the caller (JS side).
EXPORT void tuidaw_set_track_samples(int id, float* samples, int len) {
    TrackState* tk = find_track(id);
    if (!tk) return;
    tk->samples = samples;
    tk->samples_len = len;
}

EXPORT void tuidaw_set_track_volume(int id, float volume) {
    TrackState* tk = find_track(id);
    if (!tk) return;
    atomic_store(&tk->volume, volume);
}

EXPORT void tuidaw_set_track_pan(int id, float pan) {
    TrackState* tk = find_track(id);
    if (!tk) return;
    atomic_store(&tk->pan, pan);
}

EXPORT void tuidaw_set_track_muted(int id, int muted) {
    TrackState* tk = find_track(id);
    if (!tk) return;
    atomic_store(&tk->muted, muted);
}

EXPORT void tuidaw_set_track_solo(int id, int solo) {
    TrackState* tk = find_track(id);
    if (!tk) return;
    atomic_store(&tk->solo, solo);
}

// Set the capture device index for a track. -1 = default.
EXPORT void tuidaw_set_track_input_device(int id, int device_index) {
    TrackState* tk = find_track(id);
    if (!tk) return;
    tk->rec_device_index = device_index;
}

// ── Transport ───────────────────────────────────────────────────────────────

// Start playback from the given sample position.
// The playback device must already be started.
EXPORT void tuidaw_play(long position) {
    g_engine.transport_start_pos = position;
    atomic_store(&g_engine.playhead_samples, position);
    // Reset WSOLA states so each track re-syncs to the new position
    for (int i = 0; i < MAX_TRACKS; i++) {
        if (g_engine.tracks[i].active) {
            wsola_reset(&g_engine.tracks[i].wsola, (double)position);
        }
    }
    // Set click counter to the output-space equivalent of the playhead position.
    // The click buffer has beat tones at absolute positions (beat 0 at sample 0,
    // beat 1 at 60/bpm * sampleRate, etc.). By setting the counter to position/speed,
    // the counter indexes the correct absolute position in the click buffer so that
    // clicks only fire on actual beat positions — NOT at the playhead position.
    // This fixes the bug where pausing and resuming from an off-beat position would
    // cause a click to fire immediately on resume.
    {
        float speed = atomic_load(&g_engine.playback_speed);
        long click_pos = (speed > 0.01f) ? (long)((double)position / (double)speed) : position;
        atomic_store(&g_engine.click_frame_counter, click_pos);
    }
    atomic_store(&g_engine.playing, 1);
}

// Stop transport.
EXPORT void tuidaw_stop(void) {
    atomic_store(&g_engine.playing, 0);
}

// Get current playhead position in samples.
EXPORT long tuidaw_get_playhead(void) {
    return atomic_load(&g_engine.playhead_samples);
}

// Set playhead position (for scrubbing — works during playback too).
// Resets WSOLA states so all tracks re-sync to the new position.
EXPORT void tuidaw_set_playhead(long position) {
    atomic_store(&g_engine.playhead_samples, position);
    // Reset WSOLA states so each track re-syncs to the new position
    for (int i = 0; i < MAX_TRACKS; i++) {
        if (g_engine.tracks[i].active) {
            wsola_reset(&g_engine.tracks[i].wsola, (double)position);
        }
    }
    // Set click counter to the output-space equivalent of the new position.
    // Same logic as tuidaw_play: counter = position / speed so the click buffer
    // is indexed at the correct absolute beat-grid position.
    {
        float speed = atomic_load(&g_engine.playback_speed);
        long click_pos = (speed > 0.01f) ? (long)((double)position / (double)speed) : position;
        atomic_store(&g_engine.click_frame_counter, click_pos);
    }
}

// ── Click / Metronome ───────────────────────────────────────────────────────

EXPORT void tuidaw_set_click(int enabled, float bpm) {
    (void)bpm; // BPM is baked into click_samples by tuidaw_generate_click
    atomic_store(&g_engine.click_enabled, enabled);
    // Set click counter to current playhead position in output-space.
    // This ensures the click re-syncs to the beat grid when toggled on/off.
    {
        long pos = atomic_load(&g_engine.playhead_samples);
        float speed = atomic_load(&g_engine.playback_speed);
        long click_pos = (speed > 0.01f) ? (long)((double)pos / (double)speed) : pos;
        atomic_store(&g_engine.click_frame_counter, click_pos);
    }
}

// GCD helper for click buffer generation
static int click_gcd(int a, int b) {
    if (a < 0) a = -a;
    if (b < 0) b = -b;
    while (b) { int t = b; b = a % b; a = t; }
    return a;
}

// Generate and store a click buffer internally.
// Creates a buffer of duration_frames samples containing click tones (960 samples
// of 1kHz sine + 20ms linear decay) placed at GCD-exact integer beat positions.
// The buffer is owned by the native engine (malloc'd) and freed on regenerate/deinit.
//
// Beat positions use GCD-exact integer arithmetic for zero cumulative drift:
//   bpmScaled = round(bpm * 100)
//   totalScaled = SAMPLE_RATE * 60 * 100
//   N = bpmScaled / gcd(bpmScaled, totalScaled)
//   samplesPerN = N * SAMPLE_RATE * 60 / bpm  (exact integer)
//   beat k position = floor(k * samplesPerN / N)
//
// The buffer is NOT looped — the callback reads click_samples[counter] with
// a bounds check. When counter exceeds the buffer length, silence is output.
//
// Returns 0 on success, -1 on failure (allocation error or invalid params).
EXPORT int tuidaw_generate_click(float bpm, int duration_frames) {
    if (bpm <= 0.0f || duration_frames <= 0) return -1;

    // Click tone parameters
    const int tone_len = (int)(SAMPLE_RATE * 0.02f + 0.5f); // 20ms = 960 samples

    // GCD-exact beat position math:
    // We compute beat positions using integer arithmetic so there is zero
    // floating-point drift. The key insight: for N beats, the total samples
    // (N * 60 * SAMPLE_RATE / bpm) is an exact integer when N = bpm_scaled / gcd(bpm_scaled, total_scaled).
    // Within these N beats, beat k starts at floor(k * samples_per_N / N) — pure integer division.
    const int bpm_scaled = (int)(bpm * 100.0f + 0.5f);
    const int total_per_minute = SAMPLE_RATE * 60;
    const long total_scaled = (long)total_per_minute * 100L;
    const int d = click_gcd(bpm_scaled, (int)total_scaled);
    const int N = bpm_scaled / d;
    // samples_per_N = N * total_per_minute / bpm (exact integer by GCD construction)
    const long samples_per_N = (long)N * (long)total_per_minute * 100L / (long)bpm_scaled;

    // Disable click output while we rebuild the buffer (race-safe)
    atomic_store(&g_engine.click_samples_len, 0);

    // Allocate or realloc the buffer
    if (duration_frames > g_engine.click_samples_capacity) {
        float* new_buf = (float*)realloc(g_engine.click_samples, (size_t)duration_frames * sizeof(float));
        if (!new_buf) return -1;
        g_engine.click_samples = new_buf;
        g_engine.click_samples_capacity = duration_frames;
    }

    // Zero the buffer (silence)
    memset(g_engine.click_samples, 0, (size_t)duration_frames * sizeof(float));

    // Fill in click tones at GCD-exact beat positions
    // We iterate through beats until we exceed duration_frames
    for (long beat = 0; ; beat++) {
        // Compute beat position using integer arithmetic:
        // global_beat_group = beat / N, local_beat = beat % N
        // position = global_beat_group * samples_per_N + floor(local_beat * samples_per_N / N)
        long group = beat / N;
        long local = beat % N;
        long beat_start = group * samples_per_N + (local * samples_per_N / N);

        if (beat_start >= duration_frames) break;

        // Write click tone at this position
        for (int i = 0; i < tone_len && (beat_start + i) < duration_frames; i++) {
            float t = (float)i / (float)SAMPLE_RATE;
            float envelope = 1.0f - (float)i / (float)tone_len;
            g_engine.click_samples[beat_start + i] = sinf(2.0f * (float)M_PI * 1000.0f * t) * envelope;
        }
    }

    // Enable the buffer (atomic store of length makes it visible to callback)
    atomic_store(&g_engine.click_samples_len, duration_frames);
    return 0;
}

// Keep tuidaw_set_click_samples for backward compatibility / tests,
// but note that it sets an EXTERNAL buffer (not freed by native engine).
// Prefer tuidaw_generate_click() for production use.
EXPORT void tuidaw_set_click_samples(float* samples, int len) {
    atomic_store(&g_engine.click_samples_len, 0);  // disable first (race-safe)
    // If we had a native-owned buffer, free it before switching to external
    if (g_engine.click_samples && g_engine.click_samples_capacity > 0) {
        free(g_engine.click_samples);
        g_engine.click_samples_capacity = 0;
    }
    g_engine.click_samples = samples;
    atomic_store(&g_engine.click_samples_len, len);
}

EXPORT void tuidaw_set_click_volume(float volume) {
    atomic_store(&g_engine.click_volume, volume);
}

EXPORT void tuidaw_set_click_pan(float pan) {
    if (pan < -1.0f) pan = -1.0f;
    if (pan > 1.0f) pan = 1.0f;
    atomic_store(&g_engine.click_pan, pan);
}

// ── Loop Region ─────────────────────────────────────────────────────────────

EXPORT void tuidaw_set_loop(long start, long end) {
    atomic_store(&g_engine.loop_start, start);
    atomic_store(&g_engine.loop_end, end);
}

// ── Recording ───────────────────────────────────────────────────────────────

// Start recording on a track. Opens a capture device and starts writing.
// Returns 0 on success, -1 on failure.
EXPORT int tuidaw_start_recording(int id) {
    TrackState* tk = find_track(id);
    if (!tk) return -1;

    // Allocate recording buffer if needed
    if (!tk->rec_buffer) {
        tk->rec_buffer = (float*)calloc(RECORDING_BUF_LEN, sizeof(float));
        if (!tk->rec_buffer) return -1;
    }
    atomic_store(&tk->rec_write_pos, 0);

    // Set up capture device
    ma_device_config config = ma_device_config_init(ma_device_type_capture);
    config.capture.format   = ma_format_f32;
    config.capture.channels = 1;
    config.sampleRate       = SAMPLE_RATE;
    config.dataCallback     = capture_callback;
    config.pUserData        = tk;
    config.periodSizeInFrames = 256;  // ~5.3ms

    if (tk->rec_device_index >= 0 &&
        (ma_uint32)tk->rec_device_index < g_engine.capture_count) {
        config.capture.pDeviceID = &g_engine.capture_infos[tk->rec_device_index].id;
    }

    if (ma_device_init(&g_engine.context, &config, &tk->rec_device) != MA_SUCCESS) {
        return -1;
    }

    if (ma_device_start(&tk->rec_device) != MA_SUCCESS) {
        ma_device_uninit(&tk->rec_device);
        return -1;
    }

    tk->rec_device_active = 1;
    atomic_store(&tk->recording, 1);
    return 0;
}

// Stop recording on a track. Returns the number of samples recorded.
EXPORT int tuidaw_stop_recording(int id) {
    TrackState* tk = find_track(id);
    if (!tk) return 0;

    atomic_store(&tk->recording, 0);

    if (tk->rec_device_active) {
        ma_device_uninit(&tk->rec_device);
        tk->rec_device_active = 0;
    }

    return atomic_load(&tk->rec_write_pos);
}

// Get pointer to the recording buffer and the current write position.
// The caller can copy data out of this buffer.
EXPORT float* tuidaw_get_recording_buffer(int id) {
    TrackState* tk = find_track(id);
    if (!tk || !tk->rec_buffer) return NULL;
    return tk->rec_buffer;
}

// Get current recording write position (number of samples recorded so far).
EXPORT int tuidaw_get_recording_length(int id) {
    TrackState* tk = find_track(id);
    if (!tk) return 0;
    return atomic_load(&tk->rec_write_pos);
}

// ── Speed / WSOLA control ───────────────────────────────────────────────────

// Set playback speed ratio (1.0 = normal, 0.5 = half speed, 2.0 = double).
// Clamped to [0.25, 2.0]. WSOLA time-stretch is applied when speed != 1.0.
// Always resets WSOLA states to the current playhead so that input_pos stays
// in sync when transitioning between WSOLA/non-WSOLA modes (speed crossing 1.0).
EXPORT void tuidaw_set_speed(float speed) {
    if (speed < 0.25f) speed = 0.25f;
    if (speed > 2.0f)  speed = 2.0f;
    atomic_store(&g_engine.playback_speed, speed);

    // Reset WSOLA states to current playhead position.
    // This is critical when switching between WSOLA and non-WSOLA modes:
    // without this, input_pos would be stale from whenever WSOLA was last
    // active/initialized, causing a playhead jump.
    long current_pos = atomic_load(&g_engine.playhead_samples);
    for (int i = 0; i < MAX_TRACKS; i++) {
        if (g_engine.tracks[i].active) {
            wsola_reset(&g_engine.tracks[i].wsola, (double)current_pos);
        }
    }
    // Also reset click frame counter (speed change means BPM ratio changed,
    // but click timing uses displayed_bpm directly so just reset for clean start)
    // Note: don't reset here — the click should keep ticking smoothly across
    // speed changes. The displayed_bpm is updated by JS when speed changes.
}

// Get current playback speed.
EXPORT float tuidaw_get_speed(void) {
    return atomic_load(&g_engine.playback_speed);
}

// ── Offline Render ──────────────────────────────────────────────────────────
// Render audio directly into a user-provided buffer by calling playback_callback.
// This bypasses the audio device entirely, giving deterministic, sample-exact
// output for automated testing. The engine must be in "playing" state
// (call tuidaw_play first). The buffer is interleaved stereo float (L R L R...).
// Returns the number of frames rendered (== frame_count on success).
EXPORT int tuidaw_render(float* output, int frame_count) {
    if (!output || frame_count <= 0) return 0;
    playback_callback(NULL, output, NULL, (ma_uint32)frame_count);
    return frame_count;
}
